version: "3"

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/api/
    command: "cargo watch -x run"

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: leadcardsecondround
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}
